const { Octokit } = require('@octokit/rest');
const fs = require('fs-extra');
const path = require('path');
const { execSync } = require('child_process');

class GitHubIntegration {
    constructor() {
        this.octokit = new Octokit({
            auth: process.env.GITHUB_TOKEN
        });
        this.defaultBranch = 'main';
    }

    async createPullRequest(taskResult, jiraTicket = null) {
        try {
            const repoInfo = await this.getRepositoryInfo();
            const branchName = this.generateBranchName(taskResult, jiraTicket);
            
            // Create and switch to new branch
            await this.createBranch(branchName);
            
            // Commit changes
            const commitMessage = this.generateCommitMessage(taskResult, jiraTicket);
            await this.commitChanges(commitMessage);
            
            // Push branch
            await this.pushBranch(branchName);
            
            // Create PR
            const prData = await this.createPR({
                owner: repoInfo.owner,
                repo: repoInfo.repo,
                title: this.generatePRTitle(taskResult, jiraTicket),
                body: this.generatePRDescription(taskResult, jiraTicket),
                head: branchName,
                base: this.defaultBranch
            });

            // Add labels and reviewers
            await this.enhancePR(repoInfo, prData.number, taskResult);

            return {
                success: true,
                prUrl: prData.html_url,
                prNumber: prData.number,
                branch: branchName
            };

        } catch (error) {
            console.error('Error creating PR:', error);
            return {
                success: false,
                error: error.message
            };
        }
    }

    async getRepositoryInfo() {
        try {
            // Get remote origin URL
            const remoteUrl = execSync('git config --get remote.origin.url', { encoding: 'utf8' }).trim();
            
            // Parse GitHub URL
            const match = remoteUrl.match(/github\.com[:/]([^/]+)\/([^/.]+)/);
            if (!match) {
                throw new Error('Not a GitHub repository');
            }

            return {
                owner: match[1],
                repo: match[2]
            };
        } catch (error) {
            throw new Error('Failed to get repository info: ' + error.message);
        }
    }

    generateBranchName(taskResult, jiraTicket) {
        const taskType = taskResult.taskType || 'task';
        const taskId = taskResult.taskId || Date.now();
        
        let branchName = `todo-gpt/${taskType}/${taskId}`;
        
        if (jiraTicket) {
            branchName = `${jiraTicket.key}/${taskType}/${taskId}`;
        }
        
        // Sanitize branch name
        return branchName.toLowerCase().replace(/[^a-z0-9-/]/g, '-');
    }

    generateCommitMessage(taskResult, jiraTicket) {
        let message = `feat: ${taskResult.title}`;
        
        if (taskResult.taskType === 'bugfix') {
            message = `fix: ${taskResult.title}`;
        } else if (taskResult.taskType === 'refactor') {
            message = `refactor: ${taskResult.title}`;
        }

        if (jiraTicket) {
            message += `\n\nJIRA: ${jiraTicket.key}`;
        }

        message += '\n\nGenerated by Todo-GPT';
        
        // Add implementation details
        if (taskResult.steps && taskResult.steps.length > 0) {
            message += '\n\nImplementation:';
            taskResult.steps.forEach((step, index) => {
                message += `\n- ${step.description}`;
            });
        }

        return message;
    }

    generatePRTitle(taskResult, jiraTicket) {
        let title = taskResult.title;
        
        if (jiraTicket) {
            title = `[${jiraTicket.key}] ${title}`;
        }

        // Add type prefix
        const typePrefix = {
            feature: '✨',
            bugfix: '🐛',
            refactor: '♻️',
            optimization: '⚡',
            documentation: '📝'
        };

        const prefix = typePrefix[taskResult.taskType] || '🔧';
        return `${prefix} ${title}`;
    }

    generatePRDescription(taskResult, jiraTicket) {
        let description = '## 🤖 Auto-generated by Todo-GPT\n\n';
        
        if (jiraTicket) {
            description += `**JIRA Ticket:** [${jiraTicket.key}](${jiraTicket.url})\n`;
            description += `**Status:** ${jiraTicket.status}\n`;
            description += `**Priority:** ${jiraTicket.priority}\n\n`;
        }

        description += `**Task Type:** ${taskResult.taskType}\n`;
        description += `**Priority:** ${taskResult.priority}\n\n`;

        if (taskResult.description) {
            description += `## Description\n${taskResult.description}\n\n`;
        }

        if (taskResult.requirements && taskResult.requirements.length > 0) {
            description += '## Requirements\n';
            taskResult.requirements.forEach(req => {
                description += `- ${req}\n`;
            });
            description += '\n';
        }

        if (taskResult.steps && taskResult.steps.length > 0) {
            description += '## Implementation Steps\n';
            taskResult.steps.forEach((step, index) => {
                const status = step.success ? '✅' : '❌';
                description += `${index + 1}. ${status} ${step.description}\n`;
                if (step.file) {
                    description += `   - File: \`${step.file}\`\n`;
                }
            });
            description += '\n';
        }

        // Add files changed
        if (taskResult.filesChanged && taskResult.filesChanged.length > 0) {
            description += '## Files Changed\n';
            taskResult.filesChanged.forEach(file => {
                description += `- \`${file}\`\n`;
            });
            description += '\n';
        }

        // Add test results
        if (taskResult.testResult) {
            description += '## Test Results\n';
            if (taskResult.testResult.success) {
                description += '✅ All tests passed\n\n';
            } else {
                description += '❌ Some tests failed\n';
                description += '```\n' + taskResult.testResult.error + '\n```\n\n';
            }
        }

        description += '## Review Checklist\n';
        description += '- [ ] Code follows project conventions\n';
        description += '- [ ] Tests are included and passing\n';
        description += '- [ ] Documentation is updated\n';
        description += '- [ ] No security vulnerabilities introduced\n';
        description += '- [ ] Performance impact is acceptable\n';

        return description;
    }

    async createBranch(branchName) {
        try {
            // Ensure we're on the default branch
            execSync(`git checkout ${this.defaultBranch}`, { stdio: 'inherit' });
            
            // Pull latest changes
            execSync('git pull origin ' + this.defaultBranch, { stdio: 'inherit' });
            
            // Create and checkout new branch
            execSync(`git checkout -b ${branchName}`, { stdio: 'inherit' });
            
        } catch (error) {
            throw new Error('Failed to create branch: ' + error.message);
        }
    }

    async commitChanges(message) {
        try {
            // Add all changes
            execSync('git add .', { stdio: 'inherit' });
            
            // Check if there are changes to commit
            try {
                execSync('git diff --cached --exit-code', { stdio: 'pipe' });
                // No changes to commit
                return false;
            } catch (error) {
                // There are changes, proceed with commit
            }
            
            // Commit changes
            execSync(`git commit -m "${message}"`, { stdio: 'inherit' });
            return true;
            
        } catch (error) {
            throw new Error('Failed to commit changes: ' + error.message);
        }
    }

    async pushBranch(branchName) {
        try {
            execSync(`git push -u origin ${branchName}`, { stdio: 'inherit' });
        } catch (error) {
            throw new Error('Failed to push branch: ' + error.message);
        }
    }

    async createPR(prData) {
        try {
            const response = await this.octokit.pulls.create(prData);
            return response.data;
        } catch (error) {
            throw new Error('Failed to create PR: ' + error.message);
        }
    }

    async enhancePR(repoInfo, prNumber, taskResult) {
        try {
            // Add labels based on task type
            const labels = this.generateLabels(taskResult);
            if (labels.length > 0) {
                await this.octokit.issues.addLabels({
                    owner: repoInfo.owner,
                    repo: repoInfo.repo,
                    issue_number: prNumber,
                    labels: labels
                });
            }

            // Request reviewers if configured
            const reviewers = this.getReviewers(taskResult);
            if (reviewers.length > 0) {
                await this.octokit.pulls.requestReviewers({
                    owner: repoInfo.owner,
                    repo: repoInfo.repo,
                    pull_number: prNumber,
                    reviewers: reviewers
                });
            }

        } catch (error) {
            console.error('Error enhancing PR:', error);
            // Don't throw, as PR creation was successful
        }
    }

    generateLabels(taskResult) {
        const labels = ['todo-gpt', 'automated'];
        
        // Add type-based labels
        const typeLabels = {
            feature: 'enhancement',
            bugfix: 'bug',
            refactor: 'refactoring',
            optimization: 'performance',
            documentation: 'documentation'
        };

        if (typeLabels[taskResult.taskType]) {
            labels.push(typeLabels[taskResult.taskType]);
        }

        // Add priority labels
        if (taskResult.priority === 'high' || taskResult.priority === 'urgent') {
            labels.push('priority-high');
        }

        return labels;
    }

    getReviewers(taskResult) {
        // Get reviewers from environment or config
        const reviewers = process.env.DEFAULT_REVIEWERS;
        if (reviewers) {
            return reviewers.split(',').map(r => r.trim());
        }
        return [];
    }

    async addPRComment(repoInfo, prNumber, comment) {
        try {
            await this.octokit.issues.createComment({
                owner: repoInfo.owner,
                repo: repoInfo.repo,
                issue_number: prNumber,
                body: comment
            });
        } catch (error) {
            console.error('Error adding PR comment:', error);
        }
    }

    async updatePRStatus(repoInfo, prNumber, status, description) {
        try {
            const sha = await this.getLatestCommitSha(repoInfo, prNumber);
            
            await this.octokit.repos.createCommitStatus({
                owner: repoInfo.owner,
                repo: repoInfo.repo,
                sha: sha,
                state: status, // 'pending', 'success', 'error', 'failure'
                description: description,
                context: 'todo-gpt/execution'
            });
        } catch (error) {
            console.error('Error updating PR status:', error);
        }
    }

    async getLatestCommitSha(repoInfo, prNumber) {
        try {
            const response = await this.octokit.pulls.get({
                owner: repoInfo.owner,
                repo: repoInfo.repo,
                pull_number: prNumber
            });
            return response.data.head.sha;
        } catch (error) {
            throw new Error('Failed to get commit SHA: ' + error.message);
        }
    }
}

module.exports = GitHubIntegration;